### ISSUE TITLE
problems after switching to another activity

### ISSUE THREAD

**Issue by rehacktive** [carlonzo/StikkyHeader#37] opened 2015-04-15 17:11 UTC
Hi, I'm using your library in this way:
-a main activity with viewpager;
-each fragment contains an header and a recyclerview, animated through your library;

It works perfectly unless I go from a fragment to another activity, when I go back all the scroll is messed up, the header is gone somewhere and there's a lot of "empty" space.

I can provide more details or code if you need, but basically I only do:

        StikkyHeaderBuilder.stickTo(mRecyclerView)
                .setHeader(R.id.header, (ViewGroup) getView())
                .animator(new ParallaxStikkyAnimator())
                .build();

and the animator is:

    private class ParallaxStikkyAnimator extends HeaderStikkyAnimator {
        @Override
        public AnimatorBuilder getAnimatorBuilder() {
            View mHeader_image = getHeader().findViewById(R.id.header_image);
            return AnimatorBuilder.create().applyVerticalParallax(mHeader_image);
        }
    }
Is there some specific command to "restore" the recyclerview to a "good" status?

**Comment by carlonzo** [comment] 2015-04-15 18:43
Hi,
the problem is related in somehow to this issue https://github.com/carlonzo/StikkyHeader/issues/36
To solve your problem, currently I am using a workaround:

you should replace the scrollListener, get the scrollY, translate manually the header, and save/restore  the value mScrollY in/from the savedInstance. like that:
```java
mRecyclerView.setOnScrollListener(new RecyclerView.OnScrollListener() {
      @Override
      public void onScrolled(final RecyclerView recyclerView, final int dx, final int dy) {
        super.onScrolled(recyclerView, dx, dy);
        mScrollY += dy;
        header.setTranslationY(Math.max(-mScrollY, yourAnimator.getMaxTransaction()));
      }
    });

void onSaveInstance(Bundle outState){
   outState.putInt(ARG_SCROLLED_Y,mScrollY)
}

void onViewCreated(....,Bundle instance){
   if(instance != null){
      mScrollY = instance.getInt(ARG_SCROLLED_Y)
   }
}

```

this workaround should work. I am still thinking how I can solve this issue from lib side. Any suggestion its really appreciated!

**Comment by rehacktive** [comment] 2015-04-16 09:21
I've tried, same behaviour.

**Comment by carlonzo** [comment] 2015-05-03 00:16
should be fixed by https://github.com/carlonzo/StikkyHeader/pull/40

**Closed by carlonzo** 2015-05-03 00:16 UTC
Labels: bug
